### ISSUE TITLE
Social icons can be improved.

### ISSUE THREAD

**Issue by sahilsaini110** [yagarea/blackblog#6]

**Comment by sahilsaini110** [comment]
I would love to do this.

**Comment by yagarea** [comment]
That would be nice. Can you provide description of what would you do ? 
Maybe it would be better to use vector graphics like svg.

I insist on not loading any external sources or use any copyrighted art so I do need worry about crediting of licenses.

**Comment by sahilsaini110** [comment]
I would like to replace them by SVGs available at https://fontawesome.com/

**Comment by yagarea** [comment]
> I would like to replace them by SVGs available at https://fontawesome.com/

I don't know, I do not find this solution appealing. Current icons has same shape so it makes nice visual table. Fontawesome icons are minimallistic but irregular. If you want to use them it would need whole redesign of contact page.

I remind again that I will not accept solution loading external sources. All icons needs to be in `assets` folder. For this reason make sure they are public domain/open source so there will not be any problem with licensing.

**Comment by yagarea** [comment]
@sahilsaini110  If you lost your interest, please close this issue.
